# Data Preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('training.csv')
dataset_ = pd.read_csv('testing.csv')

In [3]:
dataset.head()

class  BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  Mean_R  \
0       car      1.27    91   0.97  231.38     1.39     1.47  207.92  241.74   
1  concrete      2.36   241   1.56  216.15     2.46     2.51  187.85  229.39   
2  concrete      2.12   266   1.47  232.18     2.07     2.21  206.54  244.22   
3  concrete      2.42   399   1.28  230.40     2.49     2.73  204.60  243.27   
4  concrete      2.15   944   1.73  193.18     2.28     4.10  165.98  205.55   

   Mean_NIR  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  GLCM2_140  \
0    244.48  ...       26.18    2.00       0.50      0.85       6.29   
1    231.20  ...       22.29    2.25       0.79      0.55       8.42   
2    245.79  ...       15.59    2.19       0.76      0.74       7.24   
3    243.32  ...       13.51    3.34       0.82      0.74       7.44   
4    208.00  ...       15.65   50.08       0.85      0.49       8.15   

   Dens_140  Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0      1.67       0.70     -0.08             56    3806.36  
1      1.38       0.81     -0.09           1746    1450.14  
2      1.68       0.81     -0.07            566    1094.04  
3      1.36       0.92     -0.09           1178    1125.38  
4      0.23       1.00     -0.08           6232    1146.38  

[5 rows x 148 columns]

In [4]:
dataset_.head()

class  BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  Mean_R  \
0  concrete      1.32   131   0.81  222.74     1.66     2.18  192.94  235.11   
1    shadow      1.59   864   0.94   47.56     1.41     1.87   36.82   48.78   
2    shadow      1.41   409   1.00   51.38     1.37     1.53   41.72   51.96   
3      tree      2.58   187   1.91   70.08     3.41     3.11   93.13   55.20   
4   asphalt      2.60   116   2.05   89.57     3.06     3.02   73.17   94.89   

   Mean_NIR  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  GLCM2_140  \
0    240.15  ...       31.15    5.04       0.80      0.58       8.56   
1     57.09  ...       12.01    3.70       0.52      0.96       7.01   
2     60.48  ...       18.75    3.09       0.90      0.63       8.32   
3     61.92  ...       27.67    6.33       0.89      0.70       8.56   
4    100.64  ...       32.05    1.01       0.83      0.75       8.62   

   Dens_140  Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0      0.82       0.98     -0.10           1512    1287.52  
1      1.69       0.86     -0.14            196    2659.74  
2      1.38       0.84      0.10           1198     720.38  
3      1.10       0.96      0.20            524     891.36  
4      2.08       0.08     -0.10            496    1194.76  

[5 rows x 148 columns]

In [5]:
x_train = dataset.iloc[:, 1:]
y_train = dataset.iloc[:, :1]

In [6]:
x_train.head()

BrdIndx  Area  Round  Bright  Compact  ShpIndx  Mean_G  Mean_R  Mean_NIR  \
0     1.27    91   0.97  231.38     1.39     1.47  207.92  241.74    244.48   
1     2.36   241   1.56  216.15     2.46     2.51  187.85  229.39    231.20   
2     2.12   266   1.47  232.18     2.07     2.21  206.54  244.22    245.79   
3     2.42   399   1.28  230.40     2.49     2.73  204.60  243.27    243.32   
4     2.15   944   1.73  193.18     2.28     4.10  165.98  205.55    208.00   

    SD_G  ...  SD_NIR_140  LW_140  GLCM1_140  Rect_140  GLCM2_140  Dens_140  \
0  21.41  ...       26.18    2.00       0.50      0.85       6.29      1.67   
1   6.57  ...       22.29    2.25       0.79      0.55       8.42      1.38   
2   6.16  ...       15.59    2.19       0.76      0.74       7.24      1.68   
3   5.76  ...       13.51    3.34       0.82      0.74       7.44      1.36   
4  11.46  ...       15.65   50.08       0.85      0.49       8.15      0.23   

   Assym_140  NDVI_140  BordLngth_140  GLCM3_140  
0       0.70     -0.08             56    3806.36  
1       0.81     -0.09           1746    1450.14  
2       0.81     -0.07            566    1094.04  
3       0.92     -0.09           1178    1125.38  
4       1.00     -0.08           6232    1146.38  

[5 rows x 147 columns]

In [7]:
y_train.head()

class
0       car 
1  concrete 
2  concrete 
3  concrete 
4  concrete

In [8]:
#Final x_train & y_train
x_train = dataset.iloc[:, 1:].values
y_train = dataset.iloc[:, :1].values

In [9]:
x_train

array([[ 1.27000e+00,  9.10000e+01,  9.70000e-01, ..., -8.00000e-02,
         5.60000e+01,  3.80636e+03],
       [ 2.36000e+00,  2.41000e+02,  1.56000e+00, ..., -9.00000e-02,
         1.74600e+03,  1.45014e+03],
       [ 2.12000e+00,  2.66000e+02,  1.47000e+00, ..., -7.00000e-02,
         5.66000e+02,  1.09404e+03],
       ...,
       [ 2.97000e+00,  2.52000e+02,  1.73000e+00, ...,  6.00000e-02,
         9.48000e+02,  8.21840e+02],
       [ 1.57000e+00,  2.16000e+02,  1.27000e+00, ...,  9.00000e-02,
         2.54000e+02,  1.58072e+03],
       [ 2.12000e+00,  8.36000e+02,  8.80000e-01, ..., -9.00000e-02,
         3.02000e+03,  1.61155e+03]])

In [10]:
y_train

array([['car '],
       ['concrete '],
       ['concrete '],
       ['concrete '],
       ['concrete '],
       ['tree '],
       ['car '],
       ['car '],
       ['building '],
       ['tree '],
       ['building '],
       ['asphalt '],
       ['building '],
       ['grass '],
       ['shadow '],
       ['building '],
       ['tree '],
       ['soil '],
       ['building '],
       ['shadow '],
       ['pool '],
       ['shadow '],
       ['concrete '],
       ['tree '],
       ['grass '],
       ['concrete '],
       ['grass '],
       ['building '],
       ['building '],
       ['building '],
       ['asphalt '],
       ['shadow '],
       ['building '],
       ['grass '],
       ['tree '],
       ['building '],
       ['asphalt '],
       ['tree '],
       ['tree '],
       ['concrete '],
       ['soil '],
       ['tree '],
       ['building '],
       ['building '],
       ['building '],
       ['grass '],
       ['grass '],
       ['shadow '],
       ['soil '],
       ['soil ']

In [11]:
x_test = dataset_.iloc[:, 1:].values
y_test = dataset_.iloc[:, :1].values

In [12]:
x_test

array([[ 1.32000e+00,  1.31000e+02,  8.10000e-01, ..., -1.00000e-01,
         1.51200e+03,  1.28752e+03],
       [ 1.59000e+00,  8.64000e+02,  9.40000e-01, ..., -1.40000e-01,
         1.96000e+02,  2.65974e+03],
       [ 1.41000e+00,  4.09000e+02,  1.00000e+00, ...,  1.00000e-01,
         1.19800e+03,  7.20380e+02],
       ...,
       [ 2.45000e+00,  6.59000e+02,  1.38000e+00, ..., -9.00000e-02,
         2.59600e+03,  1.24303e+03],
       [ 1.90000e+00,  8.90000e+01,  1.01000e+00, ..., -1.20000e-01,
         7.26000e+02,  1.47063e+03],
       [ 2.48000e+00,  1.55000e+02,  1.68000e+00, ..., -1.10000e-01,
         2.96000e+02,  1.99125e+03]])

In [13]:
y_test

array([['concrete '],
       ['shadow '],
       ['shadow '],
       ['tree '],
       ['asphalt '],
       ['building '],
       ['asphalt '],
       ['grass '],
       ['tree '],
       ['building '],
       ['pool '],
       ['grass '],
       ['asphalt '],
       ['concrete '],
       ['grass '],
       ['asphalt '],
       ['tree '],
       ['grass '],
       ['tree '],
       ['concrete '],
       ['tree '],
       ['grass '],
       ['tree '],
       ['building '],
       ['grass '],
       ['asphalt '],
       ['car '],
       ['tree '],
       ['building '],
       ['car '],
       ['concrete '],
       ['concrete '],
       ['building '],
       ['concrete '],
       ['asphalt '],
       ['tree '],
       ['grass '],
       ['concrete '],
       ['car '],
       ['shadow '],
       ['shadow '],
       ['concrete '],
       ['building '],
       ['tree '],
       ['tree '],
       ['tree '],
       ['concrete '],
       ['building '],
       ['building '],
       ['shadow '],


## applying label encoder to class

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = y_train.reshape(len(y_train), 1)
y_train = le.fit_transform(y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [15]:
y_train

array([2, 3, 3, 3, 3, 8, 2, 2, 1, 8, 1, 0, 1, 4, 6, 1, 8, 7, 1, 6, 5, 6,
       3, 8, 4, 3, 4, 1, 1, 1, 0, 6, 1, 4, 8, 1, 0, 8, 8, 3, 7, 8, 1, 1,
       1, 4, 4, 6, 7, 7, 6, 8, 2, 2, 0, 5, 1, 8, 4, 4, 2, 2, 5, 2, 7, 4,
       1, 3, 7, 7, 3, 1, 5, 5, 5, 6, 1, 4, 6, 1, 5, 5, 1, 3, 1, 6, 1, 7,
       0, 4, 4, 7, 3, 7, 7, 4, 5, 2, 6, 4, 4, 0, 4, 2, 4, 0, 4, 1, 3, 4,
       0, 4, 4, 5, 3, 8, 4, 3, 3, 2, 2, 4, 6, 5, 8, 6, 4, 5, 3, 4, 3, 0,
       0, 3, 0, 7, 6, 5, 5, 5, 2, 1, 3, 0, 3, 0, 1, 6, 6, 8, 4, 2, 8, 6,
       3, 1, 7, 8, 0, 3, 4, 8, 8, 2, 7, 4, 4, 3])

In [16]:
y_test = le.transform(y_test)

In [17]:
y_test

array([3, 6, 6, 8, 0, 1, 0, 4, 8, 1, 5, 4, 0, 3, 4, 0, 8, 4, 8, 3, 8, 4,
       8, 1, 4, 0, 2, 8, 1, 2, 3, 3, 1, 3, 0, 8, 4, 3, 2, 6, 6, 3, 1, 8,
       8, 8, 3, 1, 1, 6, 4, 5, 2, 8, 5, 1, 4, 6, 3, 8, 6, 4, 8, 8, 1, 1,
       2, 3, 1, 1, 5, 3, 3, 4, 4, 0, 8, 6, 0, 8, 4, 1, 1, 7, 4, 1, 3, 4,
       1, 1, 3, 8, 8, 0, 8, 1, 0, 4, 8, 1, 5, 4, 7, 0, 0, 5, 8, 3, 7, 7,
       8, 6, 4, 8, 6, 0, 0, 8, 4, 1, 7, 6, 4, 6, 6, 1, 3, 3, 1, 3, 8, 8,
       4, 2, 2, 2, 6, 7, 8, 3, 0, 4, 3, 3, 6, 8, 8, 8, 6, 4, 1, 7, 8, 8,
       4, 1, 6, 8, 3, 4, 4, 1, 6, 8, 3, 8, 1, 8, 8, 8, 3, 4, 7, 3, 1, 8,
       1, 6, 1, 1, 1, 1, 1, 4, 8, 4, 8, 0, 4, 1, 1, 0, 1, 6, 7, 7, 4, 1,
       2, 1, 8, 4, 2, 1, 7, 3, 5, 3, 1, 8, 2, 1, 3, 3, 3, 3, 5, 1, 8, 4,
       5, 8, 7, 5, 3, 0, 6, 8, 1, 7, 3, 4, 7, 4, 1, 3, 3, 3, 4, 1, 1, 3,
       7, 6, 3, 3, 1, 3, 1, 8, 1, 3, 0, 4, 6, 4, 4, 4, 4, 8, 8, 8, 8, 3,
       3, 7, 4, 4, 4, 4, 1, 6, 8, 4, 4, 7, 1, 3, 0, 1, 3, 6, 8, 4, 5, 0,
       0, 0, 0, 1, 4, 3, 5, 1, 3, 4, 4, 1, 5, 0, 7,

## Applying Feature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

### Training the dataset without applying Feature Scaling to any of the Features

In [19]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.svm import SVC
#from sklearn.tree import DecisionTreeClassifier
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [20]:
y_pred = classifier.predict(x_test)
# predicted_results & real_results
print('predicted_results & real_results')
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis=1))

predicted_results & real_results
[[3 3]
 [6 6]
 [6 6]
 ...
 [3 3]
 [2 1]
 [1 1]]


## Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

#0.5029585798816568 accuracy without Feature Scaling Logistic Regression
#0.70 Logistic Regression after Feature Scaling
#0.7238658777120316 KNN
#0.6863905325443787 SVM
#0.7593688362919132 Kernel SVM
#0.7909270216962525 Naive Bayes GaussianNB
#0.7455621301775148 Naive Bayes BernoulliNB
#0.7080867850098619 Decision Tree Regression
#0.7613412228796844 Random Forest Regression

[[33  0  0  0  2  0  4  0  6]
 [ 1 74  2 13  2  0  1  3  1]
 [ 0  0 20  0  0  0  0  1  0]
 [ 0  3  2 82  1  0  0  3  2]
 [ 0  1  1  0 52  0  0  7 22]
 [ 0  1  0  0  0 12  0  0  1]
 [ 1  0  0  0  0  1 41  0  2]
 [ 0  2  1  2  7  0  0  8  0]
 [ 0  0  0  0  6  0  4  0 79]]


0.7909270216962525